version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ocr_database
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123@
      MYSQL_ROOT_PASSWORD: admin123@
      MYSQL_DATABASE: ocr_database
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "admin", "-padmin123@"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
